### ISSUE TITLE
Update the readme file

### ISSUE THREAD

**Issue by dr03ramos** [guilhXavier/agile-project-3a#29]
Today's iteration of the [README.md](https://github.com/guilhXavier/agile-project-3a/blob/main/README.md) file is adapted from a sample. We should create a new README introductory file to the repository when possible. What kind of information do we want there?

**Comment by edukatiau** [comment]
Hey @dr03ramos  , i think the same, maybe is interessant we put the features that our application has.
Sign up, Log in
Create a Racha, share it, join it...

How our application is web, we maybe remove sections "Como instalar o Rachadinha" etc...

**Comment by dr03ramos** [comment]
updated in #42
